#!/usr/bin/env python3
from argparse import ArgumentParser
from random import Random
from subprocess import DEVNULL, run
from threading import Thread
from time import sleep

def make_tgs_req(sname: str):
    run(['kvno', f'{sname}/{domain}'], stdout=DEVNULL, stderr=DEVNULL)

if __name__ == '__main__':
    parser = ArgumentParser(description='Симулятор атаки Kerberoast.')
    parser.add_argument('--domain', type=str, required=True, help='Домен для "взлома"')
    parser.add_argument('--number_of_tgs', type=int, default=1000, help='Количество TGS-REQ')
    parser.add_argument('--freq', type=int, help='Фиксированная частота запросов')
    args = parser.parse_args()
    domain = args.domain
    with open('spn_list.txt') as spn_list:
        spns = [line.strip() for line in spn_list.readlines()]
    random = Random()
    if args.freq:
        for _ in range(args.number_of_tgs):
            make_tgs_req(spns[random.randint(0, len(spns) - 1)])
            sleep(args.freq)
    else:
        for _ in range(args.number_of_tgs):
            thread = Thread(target=make_tgs_req, args=(spns[random.randint(0, len(spns) - 1)],))
            thread.start()
